server:
  port: 8091
  servlet:
    context-path: /dmsK3Service

spring:
  application:
    name: dmsBridge
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.136.182:33306/ecology?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: ecology
    password: ecology123

# ====================Log4j2=========================
logging:
  config: classpath:log4j2-prd.xml
  level:
    #打印sql时改为debug
    druid.sql: info
    de.codecentric: error
    com.alibaba.excel.analysis.v03.handlers.FormulaRecordHandler: error
log4j2:
  threadContextMap: com.alibaba.ttl.log4j2.TtlThreadContextMap

# ====================MybatisPlus====================
mybatis-plus:
  mapper-locations: classpath*:/mapping/modules/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.me.modules.*.entity,com.me.sys.*.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: none
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    call-setters-on-nulls: true
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #需要测试SQL时再打开
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl


# ====================dms=========================
dms:
  order:
    orderMainTable: formtable_main_272
    orderDetailTable2: formtable_main_272_dt2

    returnOrderMainTable: formtable_main_227
    returnOrderDetailTable2: formtable_main_227_dt2

    newReturnOrderMainTable: formtable_main_263
    newReturnOrderDetailTable2: formtable_main_263_dt2

    trfOrderDetailTable2: formtable_main_228_dt2

    purInMainTable: formtable_main_234

    purInDetailTable2: formtable_main_234_dt2

    rePurDtlTable2: formtable_main_233_dt2

    setDtlTable3: formtable_main_242_dt3

    tranCodeDtlTable2: formtable_main_244_dt2

  ip: http://39.108.136.182:8080/
  url: /api/workflow/paService/submitRequest

bos:
  sipAppKey: nea@burgeon.com.cn
  appSecret: bos31
  url: http://192.168.0.191:9991/servlets/binserv/Rest


#富仑
fl:
  authorization: Bearer Hw_m_wYL7l8qaVuJNrgUXBYKn55YQO3w5X-Bdi5FKEo

#金蝶 暂时是用生成环境
K3:
  appId: 293236_RdbvTyvPyrB8RWxI5/1oRzVuzs0aQOmE
  dCID: 661f3771555e3a
  appSecret: be7dfad02c9d4de19585698309315157
  userName: admin1
  lCID: 2052
  serverUrl: http://kd.za-cosmetics.com/k3Cloud/

twk3:
  twAppId: 292841_S6eq6xCI3kH92+yv7e2Myx1Fzi7VRCrG
  twDCID: 6710da19a7abef
  twAppSecret: d34572a11101458d85fd0670076f49c9
  twUserName: admin1
  lCID: 2052
  serverUrl: http://kd.za-cosmetics.com/k3Cloud/

